python train.py -model neuron_small_plus \
                -batch_per_gpu 4 \
                -epochs 2000 \
                -save_every 10 \
                -out out \
                -cfg config/RESIN_small_plus.yaml \
                -slurm \
                -slurm_ngpus 8 \
                -slurm_nnodes 1 \
                -slurm_nodelist c003 \
                -slurm_partition compute \
                -reset