python train.py -model neuron_dev \
                -arch RESIN \
                -dataset tif_dataset \
                -trainer trainer \
                -gpus 0 \
                -batch_per_gpu 8 \
                -epochs 2000 \
                -save_every 5 \
                -out out \
                -cfg config/RESIN.yaml \
                -slurm \
                -slurm_ngpus 2 \
                -slurm_nnodes 1 \
                -slurm_nodelist c003 \
                -slurm_partition compute \
                -reset