python train.py -model neuron_tiny \
                -batch_per_gpu 4 \
                -epochs 1000 \
                -save_every 10 \
                -out out \
                -cfg config/RESIN_tiny.yaml \
                -slurm \
                -slurm_ngpus 8 \
                -slurm_nnodes 1 \
                -slurm_nodelist c001 \
                -slurm_partition compute \
                -reset