python train.py -model neuron_base \
                -batch_per_gpu 4 \
                -epochs 2000 \
                -save_every 10 \
                -out out \
                -cfg config/RESIN_base.yaml \
                -slurm \
                -slurm_ngpus 8 \
                -slurm_nnodes 1 \
                -slurm_nodelist c004 \
                -slurm_partition compute \
                -reset