python train.py -model t060c \
                -batch_per_gpu 4 \
                -epochs 4000 \
                -save_every 10 \
                -out out \
                -cfg config/RESIN_t060c.yaml \
                -slurm \
                -slurm_ngpus 8 \
                -slurm_nnodes 1 \
                -slurm_nodelist c003 \
                -slurm_partition compute \
                -reset