# general settings
name: projection_cyclegan
model_type: Projection_CycleGAN_Model
num_gpu: 1  # set num_gpu: 0 for cpu mode
manual_seed: 0

# dataset and data loader settings
datasets:
  train:
    name: Projection_CycleGAN
    type: Projection_CycleGAN_Dataset
    dataroot_gt: /home/wangwb/workspace/sr_3dunet/datasets/rotated_blocks/train
    io_backend:
      type: disk
    test_mode: False

    use_flip: true
    use_rot: true
    gt_size: 64 # fullsize is 128
    aniso_dimension: -1 # -3/-2/-1 <--> 0/1/2, means anisotropic in dimension 2

    # data loader
    use_shuffle: true
    num_worker_per_gpu: 12
    batch_size_per_gpu: 64
    dataset_enlarge_ratio: 1
    prefetch_mode: ~
    pin_memory: True

# network structures
network_g_A:
  type: Real2Fake_Generator
  input_nc: 1
  output_nc: 1
  ngf: 64

network_g_B:
  type: Fake2Real_Generator
  input_nc: 1
  output_nc: 1
  ngf: 64

network_d_A:
  type: Real2Fake_Discriminator
  input_nc: 1
  ndf: 64
  n_layers: 3

network_d_B:
  type: Fake2Real_Discriminator
  input_nc: 1
  ndf: 64
  n_layers: 3

# path
path:
  pretrain_network_g_A: ~
  pretrain_network_g_B: ~
  pretrain_network_d_A: ~
  pretrain_network_d_B: ~
  param_key_g: params
  strict_load_g: true
  strict_load_d: true
  resume_state: ~
  # param_key_d: ??? how to use

# training settings
train:
  optim_g_A:
    type: Adam
    lr: !!float 1e-4
    weight_decay: 0
    betas: [0.9, 0.99]
  optim_g_B:
    type: Adam
    lr: !!float 1e-4
    weight_decay: 0
    betas: [0.9, 0.99]
  lr_flow: !!float 1e-5
  optim_d_A:
    type: Adam
    lr: !!float 1e-4
    weight_decay: 0
    betas: [0.9, 0.99]
  optim_d_B:
    type: Adam
    lr: !!float 1e-4
    weight_decay: 0
    betas: [0.9, 0.99]

  scheduler:
    type: MultiStepLR
    milestones: [300000]
    gamma: 0.5

  total_iter: 300000
  warmup_iter: -1  # no warm up
  fix_flow: ~

  # losses
  cycle_opt:
    type: L1Loss
    loss_weight: 1.0
    reduction: mean
  gan_opt:
    type: GANLoss
    gan_type: lsgan
    real_label_val: 1.0
    fake_label_val: 0.0
    loss_weight: !!float 1.0    # 0.1??? # TODO

  net_d_iters: 1
  net_d_init_iters: 0

# no validate
# validation settings
# val:
#   val_freq: !!float 5e3
#   save_img: true

# logging settings
logger:
  print_freq: 100
  save_checkpoint_freq: !!float 100
  use_tb_logger: true
  wandb:
    project: ~
    resume_id: ~

# dist training settings
dist_params:
  backend: nccl
  port: 29501

find_unused_parameters: true