# general settings
name: train_self
model_type: Train_Self_3D
num_gpu: 1  # set num_gpu: 0 for cpu mode
manual_seed: 0

# # USM the ground-truth
# l1_gt_usm: False
# percep_gt_usm: False
# gan_gt_usm: False

# dataset and data loader settings
datasets:
  train:
    name: rotated_blocks
    type: Unet_3D_Dataset
    dataroot_gt: /home/wangwb/workspace/sr_3dunet/datasets/rotated_blocks/train
    test_mode: False
    io_backend:
      type: disk    
    use_flip: true
    use_rot: true
    gt_size: 64 # fullsize is 128
    aniso_dimension: -1 # -3/-2/-1 <--> 0/1/2, means anisotropic in dimension 2

    # data loader
    use_shuffle: true
    num_worker_per_gpu: 10
    batch_size_per_gpu: 4 # 8 # 16
    dataset_enlarge_ratio: 1
    prefetch_mode: ~
    pin_memory: True

# network structures
network_g:
  type: UNet_3d_Generator
  in_channels: 1
  out_channels: 1
  features: [64, 128, 256, 512]
  norm_type: batch
  dim: 3

# path
path:
  pretrain_network_g: ~
  param_key_g: params
  strict_load_g: true
  resume_state: ~
  # param_key_d: ??? how to use

# training settings
train:
  ema_decay: 0 # 0.999
  optim_g:
    type: Adam
    lr: !!float 1e-4
    weight_decay: 0
    betas: [0.9, 0.99]
  lr_flow: !!float 1e-5
  optim_d:
    type: Adam
    lr: !!float 1e-4
    weight_decay: 0
    betas: [0.9, 0.99]

  scheduler:
    type: MultiStepLR
    milestones: [300000]
    gamma: 0.5

  total_iter: 300000
  warmup_iter: -1  # no warm up
  fix_flow: ~

  # losses
  pixel_opt:
    type: L1Loss
    loss_weight: 1.0
    reduction: mean
  ssim_opt:
    type: SSIMLoss
    loss_weight : 1.0
    data_range: 1
    size_average: True
    win_size: 11
    win_sigma: 1.5
    channel: 1

  net_d_iters: 1
  net_d_init_iters: 0

# validation settings
#val:
#  val_freq: !!float 1e4
#  save_img: true

# logging settings
logger:
  print_freq: 100
  save_checkpoint_freq: !!float 200
  use_tb_logger: true
  wandb:
    project: ~
    resume_id: ~

# dist training settings
dist_params:
  backend: nccl
  port: 29500

find_unused_parameters: true
